In [ ]:
#Preprocessing

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# 2. Tentukan Path Folder
path_folder = '/content/drive/MyDrive'

files = [
    'berita_detik_jan-apr.csv'
]

Mounted at /content/drive

In [ ]:
df = pd.read_csv(path_folder + files[0])
df.head()

,Headline,Tanggal,Link,Isi Berita
0,7 Capaian Polda Metro Sepanjang 2025,2026-01-01,https://news.detik.com/berita/d-8287136/7-capa...,Kepolisian Daerah (Polda) Metro Jaya menutup t...
1,Gibran Angkat Bicara soal Pembangunan IKN,2026-01-01,https://finance.detik.com/infrastruktur/d-8287...,Pembangunan Ibu Kota Nusantara (IKN) di Kalima...
2,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ...",2026-01-01,https://www.detik.com/bali/wisata/d-8287190/ku...,Kunjungan wisatawan mancanegara ke Bali meleji...
3,"China Tegaskan Niat Reunifikasi, Taiwan Bertek...",2026-01-02,https://news.detik.com/dw/d-8288417/china-tega...,"Dalam pidato Tahun Baru, Presiden Taiwan Lai C..."
4,Kehadiran Negara dan Efektivitas Penanganan Be...,2026-01-02,https://news.detik.com/kolom/d-8288430/kehadir...,Kehadiran Presiden Prabowo Subianto di lokasi ...

#Remove Duplicate and Null

In [ ]:
# Menghapus baris yang isinya sama persis
df.drop_duplicates(inplace=True)

df.drop_duplicates(subset=['Headline'], inplace=True)


print("Jumlah duplikat setelah dihapus:", df.duplicated().sum())

Jumlah duplikat setelah dihapus: 0

In [ ]:
df = df.dropna()

In [ ]:
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

#Gabung Headline dan Isi Berita

In [ ]:
# FUNGSI GABUNG HEADLINE + 5 KALIMAT
def gabung_headline_isi(row):
    headline = str(row['Headline']).strip()
    isi_mentah = str(row['Isi Berita'])

    list_kalimat = isi_mentah.split('.')

    kalimat_valid = [k.strip() for k in list_kalimat if len(k.strip()) > 20]


    lima_kalimat = '. '.join(kalimat_valid[:5])

    return headline + ". " + lima_kalimat + "."
#buat kolom baru
df['teks_gabung'] = df.apply(gabung_headline_isi, axis=1)

In [ ]:
df.head()

,Headline,Tanggal,Link,Isi Berita,teks_gabung
0,7 Capaian Polda Metro Sepanjang 2025,2026-01-01,https://news.detik.com/berita/d-8287136/7-capa...,Kepolisian Daerah (Polda) Metro Jaya menutup t...,7 Capaian Polda Metro Sepanjang 2025. Kepolisi...
1,Gibran Angkat Bicara soal Pembangunan IKN,2026-01-01,https://finance.detik.com/infrastruktur/d-8287...,Pembangunan Ibu Kota Nusantara (IKN) di Kalima...,Gibran Angkat Bicara soal Pembangunan IKN. Pem...
2,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ...",2026-01-01,https://www.detik.com/bali/wisata/d-8287190/ku...,Kunjungan wisatawan mancanegara ke Bali meleji...,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ..."
3,"China Tegaskan Niat Reunifikasi, Taiwan Bertek...",2026-01-02,https://news.detik.com/dw/d-8288417/china-tega...,"Dalam pidato Tahun Baru, Presiden Taiwan Lai C...","China Tegaskan Niat Reunifikasi, Taiwan Bertek..."
4,Kehadiran Negara dan Efektivitas Penanganan Be...,2026-01-02,https://news.detik.com/kolom/d-8288430/kehadir...,Kehadiran Presiden Prabowo Subianto di lokasi ...,Kehadiran Negara dan Efektivitas Penanganan Be...

#Text Cleaning for Data ML

#Teks CLeaning

In [ ]:
import re
import string

emoji_pattern = re.compile("["        
    u"\U0001F600-\U0001F64F"
    u"\U0001F300-\U0001F5FF"
    u"\U0001F680-\U0001F6FF"
    u"\U0001F1E0-\U0001F1FF"
    u"\U00002702-\U000027B0"
    u"\U000024C2-\U0001F251"
    "]+", flags=re.UNICODE)

def cleaningText(text):
    if not isinstance(text, str):
        return ''                                

    text = re.sub(r'@[A-Za-z0-9]+', '', text)     # hapus mention
    text = re.sub(r'#[A-Za-z0-9]+', '', text)     # hapus hashtag
    text = re.sub(r'RT[\s]', '', text)            # hapus retweet
    text = re.sub(r'http\S+', '', text)           # hapus URL
    text = emoji_pattern.sub(r'', text)           
    text = text.replace('\n', ' ')              
    text = re.sub(r'[^A-Za-z ]+', '', text)       # hapus non-alfabet (angka, punctuation, sisa emoji)
    text = re.sub(r'\s+', ' ', text).strip()      

    return text

df['data_clean'] = df['teks_gabung'].apply(cleaningText)
df.head()

,Headline,Tanggal,Link,Isi Berita,teks_gabung,data_clean
0,7 Capaian Polda Metro Sepanjang 2025,2026-01-01,https://news.detik.com/berita/d-8287136/7-capa...,Kepolisian Daerah (Polda) Metro Jaya menutup t...,7 Capaian Polda Metro Sepanjang 2025. Kepolisi...,Capaian Polda Metro Sepanjang Kepolisian Daera...
1,Gibran Angkat Bicara soal Pembangunan IKN,2026-01-01,https://finance.detik.com/infrastruktur/d-8287...,Pembangunan Ibu Kota Nusantara (IKN) di Kalima...,Gibran Angkat Bicara soal Pembangunan IKN. Pem...,Gibran Angkat Bicara soal Pembangunan IKN Pemb...
2,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ...",2026-01-01,https://www.detik.com/bali/wisata/d-8287190/ku...,Kunjungan wisatawan mancanegara ke Bali meleji...,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ...",Kunjungan Wisman ke Bali Melejit Saat Nataru T...
3,"China Tegaskan Niat Reunifikasi, Taiwan Bertek...",2026-01-02,https://news.detik.com/dw/d-8288417/china-tega...,"Dalam pidato Tahun Baru, Presiden Taiwan Lai C...","China Tegaskan Niat Reunifikasi, Taiwan Bertek...",China Tegaskan Niat Reunifikasi Taiwan Berteka...
4,Kehadiran Negara dan Efektivitas Penanganan Be...,2026-01-02,https://news.detik.com/kolom/d-8288430/kehadir...,Kehadiran Presiden Prabowo Subianto di lokasi ...,Kehadiran Negara dan Efektivitas Penanganan Be...,Kehadiran Negara dan Efektivitas Penanganan Be...

#casefolding

In [ ]:
#Lowercase
df['data_clean'] = df['data_clean'].apply(lambda x: str(x).lower() if pd.notnull(x) else '')
df.head()

,Headline,Tanggal,Link,Isi Berita,teks_gabung,data_clean
0,7 Capaian Polda Metro Sepanjang 2025,2026-01-01,https://news.detik.com/berita/d-8287136/7-capa...,Kepolisian Daerah (Polda) Metro Jaya menutup t...,7 Capaian Polda Metro Sepanjang 2025. Kepolisi...,capaian polda metro sepanjang kepolisian daera...
1,Gibran Angkat Bicara soal Pembangunan IKN,2026-01-01,https://finance.detik.com/infrastruktur/d-8287...,Pembangunan Ibu Kota Nusantara (IKN) di Kalima...,Gibran Angkat Bicara soal Pembangunan IKN. Pem...,gibran angkat bicara soal pembangunan ikn pemb...
2,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ...",2026-01-01,https://www.detik.com/bali/wisata/d-8287190/ku...,Kunjungan wisatawan mancanegara ke Bali meleji...,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ...",kunjungan wisman ke bali melejit saat nataru t...
3,"China Tegaskan Niat Reunifikasi, Taiwan Bertek...",2026-01-02,https://news.detik.com/dw/d-8288417/china-tega...,"Dalam pidato Tahun Baru, Presiden Taiwan Lai C...","China Tegaskan Niat Reunifikasi, Taiwan Bertek...",china tegaskan niat reunifikasi taiwan berteka...
4,Kehadiran Negara dan Efektivitas Penanganan Be...,2026-01-02,https://news.detik.com/kolom/d-8288430/kehadir...,Kehadiran Presiden Prabowo Subianto di lokasi ...,Kehadiran Negara dan Efektivitas Penanganan Be...,kehadiran negara dan efektivitas penanganan be...

#Stopword & Stemming

In [ ]:
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 7.9 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [ ]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import nltk
from nltk.corpus import stopwords

# Download data stopword dari NLTK
nltk.download('stopwords')
nltk.download('punkt')

# Inisialisasi Stemmer Sastrawi
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Load Stopwords Bahasa Indonesia
list_stopwords = set(stopwords.words('indonesian'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
# 1. Load Stopwords & Custom Noise
list_stopwords = set(stopwords.words('indonesian'))
additional_noise = {'scroll', 'to', 'continue', 'with', 'content', 'detik'}
list_stopwords.update(additional_noise)

# 2. Eksekusi Stopword
print("Sedang menghapus stopwords...")
df['data_stopword'] = df['data_clean'].apply(lambda x: " ".join([t for t in x.split() if t.lower() not in list_stopwords]))

print("sesesai!")

Sedang menghapus stopwords...
sesesai!

In [ ]:
# 3. Eksekusi Stemming
print("Sedang memproses Stemming... Mohon tunggu.")
df['data_lemma'] = df['data_stopword'].apply(lambda x: stemmer.stem(x))

print('selesai!')

df.head()

Sedang memproses Stemming... Mohon tunggu.
selesai!

,Headline,Tanggal,Link,Isi Berita,teks_gabung,data_clean,data_stopword,data_lemma
0,7 Capaian Polda Metro Sepanjang 2025,2026-01-01,https://news.detik.com/berita/d-8287136/7-capa...,Kepolisian Daerah (Polda) Metro Jaya menutup t...,7 Capaian Polda Metro Sepanjang 2025. Kepolisi...,capaian polda metro sepanjang kepolisian daera...,capaian polda metro kepolisian daerah polda me...,capai polda metro polisi daerah polda metro ja...
1,Gibran Angkat Bicara soal Pembangunan IKN,2026-01-01,https://finance.detik.com/infrastruktur/d-8287...,Pembangunan Ibu Kota Nusantara (IKN) di Kalima...,Gibran Angkat Bicara soal Pembangunan IKN. Pem...,gibran angkat bicara soal pembangunan ikn pemb...,gibran angkat bicara pembangunan ikn pembangun...,gibran angkat bicara bangun ikn bangun kota nu...
2,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ...",2026-01-01,https://www.detik.com/bali/wisata/d-8287190/ku...,Kunjungan wisatawan mancanegara ke Bali meleji...,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ...",kunjungan wisman ke bali melejit saat nataru t...,kunjungan wisman bali melejit nataru turis aus...,kunjung wisman bal lejit nataru turis australi...
3,"China Tegaskan Niat Reunifikasi, Taiwan Bertek...",2026-01-02,https://news.detik.com/dw/d-8288417/china-tega...,"Dalam pidato Tahun Baru, Presiden Taiwan Lai C...","China Tegaskan Niat Reunifikasi, Taiwan Bertek...",china tegaskan niat reunifikasi taiwan berteka...,china tegaskan niat reunifikasi taiwan berteka...,china tegas niat reunifikasi taiwan tekad merd...
4,Kehadiran Negara dan Efektivitas Penanganan Be...,2026-01-02,https://news.detik.com/kolom/d-8288430/kehadir...,Kehadiran Presiden Prabowo Subianto di lokasi ...,Kehadiran Negara dan Efektivitas Penanganan Be...,kehadiran negara dan efektivitas penanganan be...,kehadiran negara efektivitas penanganan bencan...,hadir negara efektivitas tangan bencana hadir ...

#Tokenization & detokenization

In [ ]:
# SEL 4: Tokenizing & Detokenizing
df['data_token'] = df['data_lemma'].apply(lambda x: x.split())

In [ ]:
# Detokenize
df['detokenization'] = df['data_token'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x)

In [ ]:
df.head()

,Headline,Tanggal,Link,Isi Berita,teks_gabung,data_clean,data_stopword,data_lemma,data_token,detokenization
0,7 Capaian Polda Metro Sepanjang 2025,2026-01-01,https://news.detik.com/berita/d-8287136/7-capa...,Kepolisian Daerah (Polda) Metro Jaya menutup t...,7 Capaian Polda Metro Sepanjang 2025. Kepolisi...,capaian polda metro sepanjang kepolisian daera...,capaian polda metro kepolisian daerah polda me...,capai polda metro polisi daerah polda metro ja...,"[capai, polda, metro, polisi, daerah, polda, m...",capai polda metro polisi daerah polda metro ja...
1,Gibran Angkat Bicara soal Pembangunan IKN,2026-01-01,https://finance.detik.com/infrastruktur/d-8287...,Pembangunan Ibu Kota Nusantara (IKN) di Kalima...,Gibran Angkat Bicara soal Pembangunan IKN. Pem...,gibran angkat bicara soal pembangunan ikn pemb...,gibran angkat bicara pembangunan ikn pembangun...,gibran angkat bicara bangun ikn bangun kota nu...,"[gibran, angkat, bicara, bangun, ikn, bangun, ...",gibran angkat bicara bangun ikn bangun kota nu...
2,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ...",2026-01-01,https://www.detik.com/bali/wisata/d-8287190/ku...,Kunjungan wisatawan mancanegara ke Bali meleji...,"Kunjungan Wisman ke Bali Melejit Saat Nataru, ...",kunjungan wisman ke bali melejit saat nataru t...,kunjungan wisman bali melejit nataru turis aus...,kunjung wisman bal lejit nataru turis australi...,"[kunjung, wisman, bal, lejit, nataru, turis, a...",kunjung wisman bal lejit nataru turis australi...
3,"China Tegaskan Niat Reunifikasi, Taiwan Bertek...",2026-01-02,https://news.detik.com/dw/d-8288417/china-tega...,"Dalam pidato Tahun Baru, Presiden Taiwan Lai C...","China Tegaskan Niat Reunifikasi, Taiwan Bertek...",china tegaskan niat reunifikasi taiwan berteka...,china tegaskan niat reunifikasi taiwan berteka...,china tegas niat reunifikasi taiwan tekad merd...,"[china, tegas, niat, reunifikasi, taiwan, teka...",china tegas niat reunifikasi taiwan tekad merd...
4,Kehadiran Negara dan Efektivitas Penanganan Be...,2026-01-02,https://news.detik.com/kolom/d-8288430/kehadir...,Kehadiran Presiden Prabowo Subianto di lokasi ...,Kehadiran Negara dan Efektivitas Penanganan Be...,kehadiran negara dan efektivitas penanganan be...,kehadiran negara efektivitas penanganan bencan...,hadir negara efektivitas tangan bencana hadir ...,"[hadir, negara, efektivitas, tangan, bencana, ...",hadir negara efektivitas tangan bencana hadir ...

In [ ]:
# SAVE 
df.to_csv("preprocessing_data.csv")